### ISSUE TITLE
Array Index is wrong ? or the shape is not matching

### ISSUE THREAD

**Issue by Cybrarist** [aliraza011/ECG-with-XAI#1]
i have checked the code, and i can see that you are using the index 188 although the array  ends at 187 ? so it throws an error, but when i fix it and make it only to 187 and i make the connection between the client and server i get a shape mismatch ?

not sure what is going on, but feel free to ask questions if you need more information

**Comment by aliraza011** [comment]
Hi, the original input sequence is an array of 189  elements, including the labels as the last element at the 188 index.  We remove the label from and use the remaining array of 188 elements as input for the model, hence the array is indexed from 0-187 while the size is 188.

**Comment by aliraza011** [comment]
Hi, the original input sequence is an array of 189 elements, including the labels as the last element at the 188 index. We remove the label from and use the remaining array of 188 elements as input for the model, hence the array is indexed from 0-187 while the size is 188.
